import Str from "./modules/string/Str";
import DateTime, { DateField, WeekDay } from "./modules/dateTime/DateTime";
import Num from "./modules/number/Num";
import Throttle from "./modules/common/Throttle";
import Debounce from "./modules/common/Debounce";
import { PatternPool } from "./modules/common/PatternPool";
import Ternary from "./modules/common/Ternary";
declare class Baitu {
    /**
     * 字符串对象
     */
    readonly Str: typeof Str;
    /**
     * 字符串工具包
     */
    readonly StrUtil: {
        isBlank(str: string): boolean;
        isNotBlank(str: string): boolean;
        isEmpty(str: string): boolean;
        isNotEmpty(str: string): boolean;
        defaultIfNull(str: string, defaultStr: string): string;
        defaultIfBlank(str: string, defaultStr: string): string;
        defaultIfEmpty(str: string, defaultStr: string): string;
        isAnyBlank(...str: string[]): boolean;
        isAnyEmpty(...str: string[]): boolean;
        getPadStr(str: string, len: number, pad?: string): string;
        padStart(str: string, len: number, pad?: string): string;
        padEnd(str: string, len: number, pad?: string): string;
        chunk(str: string, chunkSize: number): string[];
        chunkCount(str: string, count: number): string[];
    };
    /**
     * 日期对象
     */
    readonly DateTime: typeof DateTime;
    /**
     * 日期工具包
     */
    readonly DateUtil: {
        date(): Date;
        dateTime(): DateTime;
        now(): number;
        parse(dateTime: string | number | DateTime | Date): Date;
        toDateTime(dateTime: string | number | DateTime | Date): DateTime;
        format(date: string | number | DateTime | Date, format?: string): string;
        formatDateTime(date?: string | number | DateTime | Date): string;
        formatDate(date?: string | number | DateTime | Date): string;
        daysOfMonth(date: DateTime | Date): number;
        daysOfYear(date: DateTime | Date): number;
        isLeapYear(date: DateTime | Date): boolean;
        compare(date1: DateTime | Date, date2: DateTime | Date, dateField?: DateField): number;
        age(date: DateTime | Date): number;
    };
    /**
     * 日期属性
     */
    readonly DateField: typeof DateField;
    /**
     * 周数，0到6
     */
    readonly WeekDay: typeof WeekDay;
    /**
     * 数字对象
     */
    readonly Num: typeof Num;
    /**
     * 数字工具
     */
    readonly NumberUtil: {
        fixed(number: number, fractionDigits: number): number;
        fixedCut(number: number, fractionDigits: number): number;
        floor(number: number): number;
        ceil(number: number): number;
    };
    /**
     * 节流工具
     */
    readonly Throttle: typeof Throttle;
    /**
     * 防抖工具
     */
    readonly Debounce: typeof Debounce;
    /**
     * 文件工具包
     */
    readonly FileUtil: {
        getMainName(fileName: string): string;
        getTypeSimple(fileName: string): string;
        getFileTypeSimple(file: File): string;
        isTypeSimple(fileName: string, type: string): boolean;
        isFileTypeSimple(file: File, type: string): boolean;
        getHexString(file: File, len?: number): Promise<string>;
        getFileBuffer(file: File | Blob, len?: number): Promise<string | ArrayBuffer>;
        getUint8Array(file: File, len?: number): Promise<Uint8Array>;
        getTypeMagic(file: File): Promise<string>;
        isTypeMagic(file: File, type: string): Promise<boolean>;
        download(file: File, filename?: string, mime?: string): void;
    };
    /**
     * 文件类型魔数映射
     */
    readonly FileTypeMagicMap: {
        ffd8ff: string;
        "89504e47": string;
        "4749463837": string;
        "4749463839": string;
        "49492a00227105008037": string;
        "424d228c010000000000": string;
        "424d8240090000000000": string;
        "424d8e1b030000000000": string;
        "41433130313500000000": string;
        "7b5c727466315c616e73": string;
        "38425053000100000000": string;
        "46726f6d3a203d3f6762": string;
        "5374616E64617264204A": string;
        "252150532D41646F6265": string;
        "255044462d312e": string;
        "2e524d46000000120001": string;
        "464c5601050000000900": string;
        "00000020667479706d70": string;
        "49443303000000002176": string;
        "000001ba210001000180": string;
        "3026b2758e66cf11a6d9": string;
        "52494646e27807005741": string;
        "52494646d07d60074156": string;
        "4d546864000000060001": string;
        "526172211a0700cf9073": string;
        "235468697320636f6e66": string;
        "504B03040a0000000000": string;
        "504B0304140008000800": string;
        D0CF11E0A1B11AE10: string;
        "504B0304": string;
        "4d5a9000030000000400": string;
        "3c25402070616765206c": string;
        "4d616e69666573742d56": string;
        "7061636b616765207765": string;
        /**
         * 日期工具包
         */
        "406563686f206f66660d": string;
        "1f8b0800000000000000": string; /**
         * 日期属性
         */
        cafebabe0000002e0041: string;
        "49545346030000006000": string;
        "04000000010000001300": string;
        d0cf11e0a1b11ae10000: string;
        "6431303a637265617465": string;
        /**
         * 数字工具
         */
        "6D6F6F76": string;
        FF575043: string;
        CFAD12FEC5FD746F: string;
        "2142444E": string;
        AC9EBD8F: string;
        E3828596: string;
        "2E7261FD": string;
    };
    /**
     * 文件类型MIME映射
     */
    readonly FileTypeMimeMap: {
        ez: string;
        aw: string;
        atom: string;
        atomcat: string;
        atomdeleted: string;
        atomsvc: string;
        dwd: string;
        held: string;
        rsat: string;
        bdoc: string;
        xcs: string;
        ccxml: string;
        cdfx: string;
        cdmia: string;
        cdmic: string;
        cdmid: string;
        cdmio: string;
        cdmiq: string;
        cpl: string;
        cu: string;
        mpd: string;
        mpp: string;
        davmount: string;
        dbk: string;
        /**
         * 字符串对象
         */
        dssc: string;
        xdssc: string;
        es: string;
        emma: string;
        emotionml: string;
        epub: string;
        exi: string;
        exp: string;
        fdt: string;
        pfr: string;
        geojson: string;
        gml: string;
        gpx: string;
        gxf: string;
        gz: string;
        hjson: string;
        stk: string;
        ink: string;
        ipfix: string;
        its: string;
        jar: string;
        ser: string;
        class: string;
        js: string; /**
         * 16进制工具包
         */
        json: string;
        json5: string; /**
         * 对象工具包
         */
        jsonml: string;
        jsonld: string;
        lgr: string;
        lostxml: string; /**
         * 数组工具包
         */
        hqx: string;
        cpt: string;
        mads: string;
        webmanifest: string;
        mrc: string;
        mrcx: string;
        ma: string;
        mathml: string;
        mbox: string;
        mpf: string;
        mscml: string;
        metalink: string;
        meta4: string;
        mets: string;
        maei: string;
        musd: string;
        mods: string;
        m21: string;
        mp4s: string;
        doc: string;
        mxf: string;
        nq: string;
        nt: string;
        cjs: string;
        bin: string;
        oda: string;
        opf: string;
        ogx: string;
        omdoc: string;
        onetoc: string;
        oxps: string;
        relo: string;
        xer: string;
        pdf: string;
        pgp: string;
        asc: string;
        prf: string;
        p10: string;
        p7m: string;
        p7s: string;
        p8: string;
        ac: string;
        cer: string;
        crl: string;
        pkipath: string;
        pki: string;
        pls: string;
        ai: string;
        provx: string;
        cww: string;
        pskcxml: string;
        raml: string;
        rdf: string;
        rif: string;
        rnc: string;
        rl: string;
        rld: string;
        rs: string;
        rapd: string;
        sls: string;
        rusd: string;
        gbr: string;
        mft: string;
        roa: string;
        rsd: string;
        rss: string;
        rtf: string;
        sbml: string;
        scq: string;
        scs: string;
        spq: string;
        spp: string;
        sdp: string;
        senmlx: string;
        sensmlx: string;
        setpay: string;
        setreg: string;
        shf: string;
        siv: string;
        smi: string;
        rq: string;
        srx: string;
        gram: string;
        grxml: string;
        sru: string;
        ssdl: string;
        ssml: string;
        swidtag: string;
        tei: string;
        tfi: string;
        tsd: string;
        toml: string;
        trig: string;
        ttml: string;
        ubj: string;
        rsheet: string;
        td: string;
        "1km": string;
        plb: string;
        psb: string;
        pvb: string;
        tcap: string;
        pwn: string;
        aso: string;
        imp: string;
        acu: string;
        atc: string;
        air: string;
        fcdt: string;
        fxp: string;
        xdp: string;
        xfdf: string;
        age: string;
        ahead: string;
        azf: string;
        azs: string;
        azw: string;
        acc: string;
        ami: string;
        apk: string;
        cii: string;
        fti: string;
        atx: string;
        mpkg: string;
        key: string;
        m3u8: string;
        numbers: string;
        pages: string;
        pkpass: string;
        swi: string;
        iota: string;
        aep: string;
        bmml: string;
        mpm: string;
        bmi: string;
        rep: string;
        cdxml: string;
        mmd: string;
        cdy: string;
        csl: string;
        cla: string;
        rp9: string;
        c4g: string;
        c11amc: string;
        c11amz: string;
        csp: string;
        cdbcmsg: string;
        cmc: string;
        clkx: string;
        clkk: string;
        clkp: string;
        clkt: string;
        clkw: string;
        wbs: string;
        pml: string;
        ppd: string;
        car: string;
        pcurl: string;
        dart: string;
        rdz: string;
        dbf: string;
        uvf: string;
        uvt: string;
        uvx: string;
        uvz: string;
        fe_launch: string;
        dna: string;
        mlp: string;
        dpg: string;
        dfac: string;
        kpxx: string;
        ait: string;
        svc: string;
        geo: string;
        mag: string;
        nml: string;
        esf: string;
        msf: string;
        qam: string;
        slt: string;
        ssf: string;
        es3: string;
        ez2: string;
        ez3: string;
        fdf: string;
        mseed: string;
        seed: string;
        gph: string;
        ftc: string;
        fm: string;
        fnc: string;
        ltf: string;
        fsc: string;
        oas: string;
        oa2: string;
        oa3: string;
        fg5: string;
        bh2: string;
        ddd: string;
        xdw: string;
        xbd: string;
        fzs: string;
        txd: string;
        ggb: string;
        ggt: string;
        gex: string;
        gxt: string;
        g2w: string;
        g3w: string;
        gmx: string;
        gdoc: string;
        gslides: string;
        gsheet: string;
        kml: string;
        kmz: string;
        gqf: string;
        gac: string;
        ghf: string;
        gim: string;
        grv: string;
        gtm: string;
        tpl: string;
        vcg: string;
        hal: string;
        zmm: string;
        hbci: string;
        les: string;
        hpgl: string;
        hpid: string;
        hps: string;
        jlt: string;
        pcl: string;
        pclxl: string;
        "sfd-hdstx": string;
        mpy: string;
        afp: string;
        irm: string;
        sc: string;
        icc: string;
        igl: string;
        ivp: string;
        ivu: string;
        igm: string;
        xpw: string;
        i2g: string;
        qbo: string;
        qfx: string;
        rcprofile: string;
        irp: string;
        xpr: string;
        fcs: string;
        jam: string;
        rms: string;
        jisp: string;
        joda: string;
        ktz: string;
        karbon: string;
        chrt: string;
        kfo: string;
        flw: string;
        kon: string;
        kpr: string;
        ksp: string;
        kwd: string;
        htke: string;
        kia: string;
        kne: string;
        skp: string;
        sse: string;
        lasxml: string;
        lbd: string;
        lbe: string;
        "123": string;
        apr: string;
        pre: string;
        nsf: string;
        org: string;
        scm: string;
        lwp: string;
        portpkg: string;
        mvt: string;
        mcd: string;
        mc1: string;
        cdkey: string;
        mwf: string;
        mfm: string;
        flo: string;
        igx: string;
        mif: string;
        daf: string;
        dis: string;
        mbk: string;
        mqy: string;
        msl: string;
        plc: string;
        txf: string;
        mpn: string;
        mpc: string;
        xul: string;
        cil: string;
        cab: string;
        xls: string;
        xlam: string;
        xlsb: string;
        xlsm: string;
        xltm: string;
        eot: string;
        chm: string;
        ims: string;
        lrm: string;
        thmx: string;
        msg: string;
        cat: string;
        stl: string;
        ppt: string;
        ppam: string;
        pptm: string;
        sldm: string;
        ppsm: string;
        potm: string;
        docm: string;
        dotm: string;
        wps: string;
        wpl: string;
        xps: string;
        mseq: string;
        mus: string;
        msty: string;
        taglet: string;
        nlu: string;
        ntf: string;
        nnd: string;
        nns: string;
        nnw: string;
        ngdat: string;
        "n-gage": string;
        rpst: string;
        rpss: string;
        edm: string;
        edx: string;
        ext: string;
        odc: string;
        otc: string;
        odb: string;
        odf: string;
        odft: string;
        odg: string;
        otg: string;
        odi: string;
        oti: string;
        odp: string;
        otp: string;
        ods: string;
        ots: string;
        odt: string;
        odm: string;
        ott: string;
        oth: string;
        xo: string;
        dd2: string;
        obgx: string;
        oxt: string;
        osm: string;
        pptx: string;
        sldx: string;
        ppsx: string;
        potx: string;
        xlsx: string;
        xltx: string;
        docx: string;
        dotx: string;
        mgp: string;
        dp: string;
        esa: string;
        pdb: string;
        paw: string;
        str: string;
        ei6: string;
        efif: string;
        wg: string;
        plf: string;
        pbd: string;
        box: string;
        mgz: string;
        qps: string;
        ptid: string;
        qxd: string;
        rar: string;
        bed: string;
        mxl: string;
        musicxml: string;
        cryptonote: string;
        cod: string;
        rm: string;
        rmvb: string;
        link66: string;
        st: string;
        see: string;
        sema: string;
        semd: string;
        semf: string;
        ifm: string;
        itp: string;
        iif: string;
        ipk: string;
        twd: string;
        mmf: string;
        teacher: string;
        fo: string;
        sdkm: string;
        dxp: string;
        sfs: string;
        sdc: string;
        sda: string;
        sdd: string;
        smf: string;
        sdw: string;
        sgl: string;
        smzip: string;
        sm: string;
        wadl: string;
        sxc: string;
        stc: string;
        sxd: string;
        std: string;
        sxi: string;
        sti: string;
        sxm: string;
        sxw: string;
        sxg: string;
        stw: string;
        sus: string;
        svd: string;
        sis: string;
        xsm: string;
        bdm: string;
        xdm: string;
        ddf: string;
        tao: string;
        pcap: string;
        tmo: string;
        tpt: string;
        mxs: string;
        tra: string;
        ufd: string;
        utz: string;
        umj: string;
        unityweb: string;
        uoml: string;
        vcx: string;
        vsd: string;
        vis: string;
        vsf: string;
        wbxml: string;
        wmlc: string;
        wmlsc: string;
        wtb: string;
        nbp: string;
        wpd: string;
        wqd: string;
        stf: string;
        xar: string;
        xfdl: string;
        hvd: string;
        hvs: string;
        hvp: string;
        osf: string;
        osfpvg: string;
        saf: string;
        spf: string;
        cmp: string;
        zir: string;
        zaz: string;
        vxml: string;
        wasm: string;
        wif: string;
        wgt: string;
        hlp: string;
        wsdl: string;
        wspolicy: string;
        "7z": string;
        abw: string;
        ace: string;
        dmg: string;
        arj: string;
        aab: string;
        aam: string;
        aas: string;
        bcpio: string;
        torrent: string;
        blb: string;
        bz: string;
        bz2: string;
        cbr: string;
        vcd: string;
        cfs: string;
        chat: string;
        pgn: string;
        crx: string;
        cco: string;
        nsc: string;
        cpio: string;
        csh: string;
        deb: string;
        dgc: string;
        dir: string;
        wad: string;
        ncx: string;
        dtb: string;
        res: string;
        dvi: string;
        evy: string;
        eva: string;
        bdf: string;
        gsf: string;
        psf: string;
        pcf: string;
        snf: string;
        pfa: string;
        arc: string;
        spl: string;
        gca: string;
        ulx: string;
        gnumeric: string;
        gramps: string;
        gtar: string;
        hdf: string;
        php: string;
        install: string;
        iso: string;
        jardiff: string;
        jnlp: string;
        kdbx: string;
        latex: string;
        luac: string;
        lzh: string;
        run: string;
        mie: string;
        prc: string;
        application: string;
        lnk: string;
        wmd: string;
        wmz: string;
        xbap: string;
        mdb: string;
        obd: string;
        crd: string;
        clp: string;
        exe: string;
        mvb: string;
        wmf: string;
        mny: string;
        pub: string;
        scd: string;
        trm: string;
        wri: string;
        nc: string;
        pac: string;
        nzb: string;
        pl: string;
        p12: string;
        p7b: string;
        p7r: string;
        rpm: string;
        ris: string;
        sea: string;
        sh: string;
        shar: string;
        swf: string;
        xap: string;
        sql: string;
        sit: string;
        sitx: string;
        srt: string;
        sv4cpio: string;
        sv4crc: string;
        t3: string;
        gam: string;
        tar: string;
        tcl: string;
        tex: string;
        tfm: string;
        texinfo: string;
        obj: string;
        ustar: string;
        hdd: string;
        ova: string;
        ovf: string;
        vbox: string;
        "vbox-extpack": string;
        vdi: string;
        vhd: string;
        vmdk: string;
        src: string;
        webapp: string;
        der: string;
        fig: string;
        xlf: string;
        xpi: string;
        xz: string;
        z1: string;
        xaml: string;
        xav: string;
        xca: string;
        xdf: string;
        xel: string;
        xns: string;
        xenc: string;
        xhtml: string;
        xml: string;
        dtd: string;
        xop: string;
        xpl: string;
        xsl: string;
        xspf: string;
        mxml: string;
        yang: string;
        yin: string;
        zip: string;
        "3gpp": string;
        adp: string;
        amr: string;
        au: string;
        mid: string;
        mxmf: string;
        mp3: string;
        m4a: string;
        mpga: string;
        oga: string;
        s3m: string;
        sil: string;
        uva: string;
        eol: string;
        dra: string;
        dts: string;
        dtshd: string;
        lvp: string;
        pya: string;
        ecelp4800: string;
        ecelp7470: string;
        ecelp9600: string;
        rip: string;
        wav: string;
        weba: string;
        aac: string;
        aif: string;
        caf: string;
        flac: string;
        mka: string;
        m3u: string;
        wax: string;
        wma: string;
        ram: string;
        rmp: string;
        ra: string;
        xm: string;
        cdx: string;
        cif: string;
        cmdf: string;
        cml: string;
        csml: string;
        xyz: string;
        ttc: string;
        otf: string;
        ttf: string;
        woff: string;
        woff2: string;
        exr: string;
        apng: string;
        avci: string;
        avcs: string;
        avif: string;
        bmp: string;
        cgm: string;
        drle: string;
        emf: string;
        fits: string;
        g3: string;
        gif: string;
        heic: string;
        heics: string;
        heif: string;
        heifs: string;
        hej2: string;
        hsj2: string;
        ief: string;
        jls: string;
        jp2: string;
        jpeg: string;
        jph: string;
        jhc: string;
        jpm: string;
        jpx: string;
        jxr: string;
        jxra: string;
        jxrs: string;
        jxs: string;
        jxsc: string;
        jxsi: string;
        jxss: string;
        ktx: string;
        ktx2: string;
        png: string;
        btif: string;
        pti: string;
        sgi: string;
        svg: string;
        t38: string;
        tif: string;
        tfx: string;
        psd: string;
        azv: string;
        uvi: string;
        djvu: string;
        sub: string;
        dwg: string;
        dxf: string;
        fbs: string;
        fpx: string;
        fst: string;
        mmr: string;
        rlc: string;
        ico: string;
        dds: string;
        mdi: string;
        wdp: string;
        npx: string;
        b16: string;
        tap: string;
        vtf: string;
        wbmp: string;
        xif: string;
        pcx: string;
        webp: string;
        "3ds": string;
        ras: string;
        cmx: string;
        fh: string;
        jng: string;
        sid: string;
        pic: string;
        pnm: string;
        pbm: string;
        pgm: string;
        ppm: string;
        rgb: string;
        tga: string;
        xbm: string;
        xpm: string;
        xwd: string;
        "disposition-notification": string;
        u8msg: string;
        u8dsn: string;
        u8mdn: string;
        u8hdr: string;
        eml: string;
        wsc: string;
        "3mf": string;
        gltf: string;
        glb: string;
        igs: string;
        msh: string;
        mtl: string;
        stpx: string;
        stpz: string;
        stpxz: string;
        dae: string;
        dwf: string;
        gdl: string;
        gtw: string;
        mts: string;
        ogex: string;
        x_b: string;
        x_t: string;
        vds: string;
        usdz: string;
        bsp: string;
        vtu: string;
        wrl: string;
        x3db: string;
        x3dv: string;
        x3d: string;
        appcache: string;
        ics: string;
        coffee: string;
        css: string;
        csv: string;
        html: string;
        jade: string;
        jsx: string;
        less: string;
        markdown: string;
        mml: string;
        mdx: string;
        n3: string;
        txt: string;
        dsc: string;
        rtx: string;
        sgml: string;
        shex: string;
        slim: string;
        spdx: string;
        stylus: string;
        tsv: string;
        t: string;
        ttl: string;
        uri: string;
        vcard: string;
        curl: string;
        dcurl: string;
        mcurl: string;
        scurl: string;
        ged: string;
        fly: string;
        flx: string;
        gv: string;
        "3dml": string;
        spot: string;
        jad: string;
        wml: string;
        wmls: string;
        vtt: string;
        s: string;
        c: string;
        htc: string;
        f: string;
        hbs: string;
        java: string;
        lua: string;
        mkd: string;
        nfo: string;
        opml: string;
        p: string;
        pde: string;
        sass: string;
        scss: string;
        etx: string;
        sfv: string;
        ymp: string;
        uu: string;
        vcs: string;
        vcf: string;
        yaml: string;
        "3gp": string;
        "3g2": string;
        h261: string;
        h263: string;
        h264: string;
        m4s: string;
        jpgv: string;
        mj2: string;
        ts: string;
        mp4: string;
        mpeg: string;
        ogv: string;
        qt: string;
        uvh: string;
        uvm: string;
        uvp: string;
        uvs: string;
        uvv: string;
        dvb: string;
        fvt: string;
        mxu: string;
        pyv: string;
        uvu: string;
        viv: string;
        webm: string;
        f4v: string;
        fli: string;
        flv: string;
        m4v: string;
        mkv: string;
        mng: string;
        asf: string;
        vob: string;
        wm: string;
        wmv: string;
        wmx: string;
        wvx: string;
        avi: string;
        movie: string;
        smv: string;
        ice: string;
    };
    /**
     * 16进制工具包
     */
    readonly HexUtil: {
        encode(str: string): string;
        decode(hex: string): string;
        arrayBufferToHex(arrayBuffer: ArrayBuffer): string;
        uint8ArrayToHex(uint8Array: Uint8Array): string;
        hexToUint8Array(hex: string): Uint8Array;
    };
    /**
     * 对象工具包
     */
    readonly ObjectUtil: {
        isEmpty(value: any): boolean;
    };
    /**
     * 脱敏工具包
     */
    readonly DesensitizedUtil: {
        of(str: string, startIndex?: number, length?: number, pad?: string): string;
        reserve(str: string, headLen?: number, tailLen?: number, pad?: string): string;
        with(params: import("./modules/string/DesensitizedUtil").DesensitizedParam): string;
        mobile(str: string, startIndex?: number, length?: number, pad?: string): string;
        fullName(str: string, startIndex?: number, length?: number, pad?: string): string;
        fullName2(str: string): string;
        idCard(str: string, headLen?: number, tailLen?: number, pad?: string): string;
        bankAccount(str: string, headLen?: number, tailLen?: number, pad?: string): string;
        mobileWith(params: import("./modules/string/DesensitizedUtil").DesensitizedParam): string;
        fullNameWith(params: import("./modules/string/DesensitizedUtil").DesensitizedParam): string;
        idCardWith(params: import("./modules/string/DesensitizedUtil").DesensitizedReserveParam): string;
        bankAccountWith(params: import("./modules/string/DesensitizedUtil").DesensitizedReserveParam): string;
    };
    /**
     * 数组工具包
     */
    readonly ArrayUtil: {
        repeat(arr: (string | number)[], count: number): string;
        finalItem(arr: any[], defaultItem?: any): any;
        push(arr: any[], item: any): any[];
    };
    /**
     * 正则池
     */
    PatternPool: PatternPool;
    /**
     * 正则池class
     */
    PatternPollClass: typeof PatternPool;
    /**
     * 正则工具
     */
    readonly ValidateUtil: {
        validate(str: string, pattern: string | RegExp): boolean;
        isNumber(str: string): boolean;
        isChinese(str: string): boolean;
        isIPV4(str: string): boolean;
        isIPV6(str: string): boolean;
        isMoney(str: string): boolean;
        isEmail(str: string): boolean;
        isDomainName(str: string): boolean;
        isMobile(str: string): boolean;
        isLandline(str: string): boolean;
        isIdCard(str: string): boolean;
        isUrlHttp(str: string): boolean; /**
         * 数字工具
         */
        isPlateNumber(str: string): boolean;
        isDate(str: string): boolean;
        isTime(str: string): boolean;
        isBlankLine(str: string): boolean;
    };
    readonly Ternary: typeof Ternary;
    /**
     * 赋值正则池
     * @param patternPool 正则池
     */
    setPatternPool(patternPool: PatternPool): void;
    /**
     * 注入工具方法
     */
    putTo(fn: (key: any, tool: any) => {}): void;
    /**
     * 获取所有工具对象
     */
    values(): {
        Str: typeof Str;
        StrUtil: {
            isBlank(str: string): boolean;
            isNotBlank(str: string): boolean;
            isEmpty(str: string): boolean;
            isNotEmpty(str: string): boolean;
            defaultIfNull(str: string, defaultStr: string): string;
            defaultIfBlank(str: string, defaultStr: string): string;
            defaultIfEmpty(str: string, defaultStr: string): string;
            isAnyBlank(...str: string[]): boolean;
            isAnyEmpty(...str: string[]): boolean;
            getPadStr(str: string, len: number, pad?: string): string;
            padStart(str: string, len: number, pad?: string): string;
            padEnd(str: string, len: number, pad?: string): string;
            chunk(str: string, chunkSize: number): string[];
            chunkCount(str: string, count: number): string[];
        };
        DateTime: typeof DateTime;
        DateField: typeof DateField;
        WeekDay: typeof WeekDay;
        DateUtil: {
            date(): Date;
            dateTime(): DateTime;
            now(): number;
            parse(dateTime: string | number | DateTime | Date): Date;
            toDateTime(dateTime: string | number | DateTime | Date): DateTime;
            format(date: string | number | DateTime | Date, format?: string): string;
            formatDateTime(date?: string | number | DateTime | Date): string;
            formatDate(date?: string | number | DateTime | Date): string;
            daysOfMonth(date: DateTime | Date): number;
            daysOfYear(date: DateTime | Date): number;
            isLeapYear(date: DateTime | Date): boolean;
            compare(date1: DateTime | Date, date2: DateTime | Date, dateField?: DateField): number;
            age(date: DateTime | Date): number;
        };
        Num: typeof Num;
        NumberUtil: {
            fixed(number: number, fractionDigits: number): number;
            fixedCut(number: number, fractionDigits: number): number;
            floor(number: number): number;
            ceil(number: number): number;
        };
        Throttle: typeof Throttle;
        Debounce: typeof Debounce;
        FileUtil: {
            getMainName(fileName: string): string;
            getTypeSimple(fileName: string): string;
            getFileTypeSimple(file: File): string;
            isTypeSimple(fileName: string, type: string): boolean;
            isFileTypeSimple(file: File, type: string): boolean;
            getHexString(file: File, len?: number): Promise<string>;
            getFileBuffer(file: File | Blob, len?: number): Promise<string | ArrayBuffer>;
            getUint8Array(file: File, len?: number): Promise<Uint8Array>;
            getTypeMagic(file: File): Promise<string>;
            isTypeMagic(file: File, type: string): Promise<boolean>;
            download(file: File, filename?: string, mime?: string): void;
        };
        HexUtil: {
            encode(str: string): string;
            decode(hex: string): string;
            arrayBufferToHex(arrayBuffer: ArrayBuffer): string;
            uint8ArrayToHex(uint8Array: Uint8Array): string;
            hexToUint8Array(hex: string): Uint8Array;
        };
        FileTypeMagicMap: {
            ffd8ff: string;
            "89504e47": string;
            "4749463837": string;
            "4749463839": string;
            "49492a00227105008037": string;
            "424d228c010000000000": string;
            "424d8240090000000000": string;
            "424d8e1b030000000000": string;
            "41433130313500000000": string;
            "7b5c727466315c616e73": string;
            "38425053000100000000": string;
            "46726f6d3a203d3f6762": string;
            "5374616E64617264204A": string;
            "252150532D41646F6265": string;
            "255044462d312e": string;
            "2e524d46000000120001": string;
            "464c5601050000000900": string;
            "00000020667479706d70": string;
            "49443303000000002176": string;
            "000001ba210001000180": string;
            "3026b2758e66cf11a6d9": string;
            "52494646e27807005741": string;
            "52494646d07d60074156": string;
            "4d546864000000060001": string;
            "526172211a0700cf9073": string;
            "235468697320636f6e66": string;
            "504B03040a0000000000": string;
            "504B0304140008000800": string;
            D0CF11E0A1B11AE10: string;
            "504B0304": string;
            "4d5a9000030000000400": string;
            "3c25402070616765206c": string;
            "4d616e69666573742d56": string;
            "7061636b616765207765": string;
            /**
             * 日期工具包
             */
            "406563686f206f66660d": string;
            "1f8b0800000000000000": string; /**
             * 日期属性
             */
            cafebabe0000002e0041: string;
            "49545346030000006000": string;
            "04000000010000001300": string;
            d0cf11e0a1b11ae10000: string;
            "6431303a637265617465": string;
            /**
             * 数字工具
             */
            "6D6F6F76": string;
            FF575043: string;
            CFAD12FEC5FD746F: string;
            "2142444E": string;
            AC9EBD8F: string;
            E3828596: string;
            "2E7261FD": string;
        };
        FileTypeMimeMap: {
            ez: string;
            aw: string;
            atom: string;
            atomcat: string;
            atomdeleted: string;
            atomsvc: string;
            dwd: string;
            held: string;
            rsat: string;
            bdoc: string;
            xcs: string;
            ccxml: string;
            cdfx: string;
            cdmia: string;
            cdmic: string;
            cdmid: string;
            cdmio: string;
            cdmiq: string;
            cpl: string;
            cu: string;
            mpd: string;
            mpp: string;
            davmount: string;
            dbk: string;
            /**
             * 字符串对象
             */
            dssc: string;
            xdssc: string;
            es: string;
            emma: string;
            emotionml: string;
            epub: string;
            exi: string;
            exp: string;
            fdt: string;
            pfr: string;
            geojson: string;
            gml: string;
            gpx: string;
            gxf: string;
            gz: string;
            hjson: string;
            stk: string;
            ink: string;
            ipfix: string;
            its: string;
            jar: string;
            ser: string;
            class: string;
            js: string; /**
             * 16进制工具包
             */
            json: string;
            json5: string; /**
             * 对象工具包
             */
            jsonml: string;
            jsonld: string;
            lgr: string;
            lostxml: string; /**
             * 数组工具包
             */
            hqx: string;
            cpt: string;
            mads: string;
            webmanifest: string;
            mrc: string;
            mrcx: string;
            ma: string;
            mathml: string;
            mbox: string;
            mpf: string;
            mscml: string;
            metalink: string;
            meta4: string;
            mets: string;
            maei: string;
            musd: string;
            mods: string;
            m21: string;
            mp4s: string;
            doc: string;
            mxf: string;
            nq: string;
            nt: string;
            cjs: string;
            bin: string;
            oda: string;
            opf: string;
            ogx: string;
            omdoc: string;
            onetoc: string;
            oxps: string;
            relo: string;
            xer: string;
            pdf: string;
            pgp: string;
            asc: string;
            prf: string;
            p10: string;
            p7m: string;
            p7s: string;
            p8: string;
            ac: string;
            cer: string;
            crl: string;
            pkipath: string;
            pki: string;
            pls: string;
            ai: string;
            provx: string;
            cww: string;
            pskcxml: string;
            raml: string;
            rdf: string;
            rif: string;
            rnc: string;
            rl: string;
            rld: string;
            rs: string;
            rapd: string;
            sls: string;
            rusd: string;
            gbr: string;
            mft: string;
            roa: string;
            rsd: string;
            rss: string;
            rtf: string;
            sbml: string;
            scq: string;
            scs: string;
            spq: string;
            spp: string;
            sdp: string;
            senmlx: string;
            sensmlx: string;
            setpay: string;
            setreg: string;
            shf: string;
            siv: string;
            smi: string;
            rq: string;
            srx: string;
            gram: string;
            grxml: string;
            sru: string;
            ssdl: string;
            ssml: string;
            swidtag: string;
            tei: string;
            tfi: string;
            tsd: string;
            toml: string;
            trig: string;
            ttml: string;
            ubj: string;
            rsheet: string;
            td: string;
            "1km": string;
            plb: string;
            psb: string;
            pvb: string;
            tcap: string;
            pwn: string;
            aso: string;
            imp: string;
            acu: string;
            atc: string;
            air: string;
            fcdt: string;
            fxp: string;
            xdp: string;
            xfdf: string;
            age: string;
            ahead: string;
            azf: string;
            azs: string;
            azw: string;
            acc: string;
            ami: string;
            apk: string;
            cii: string;
            fti: string;
            atx: string;
            mpkg: string;
            key: string;
            m3u8: string;
            numbers: string;
            pages: string;
            pkpass: string;
            swi: string;
            iota: string;
            aep: string;
            bmml: string;
            mpm: string;
            bmi: string;
            rep: string;
            cdxml: string;
            mmd: string;
            cdy: string;
            csl: string;
            cla: string;
            rp9: string;
            c4g: string;
            c11amc: string;
            c11amz: string;
            csp: string;
            cdbcmsg: string;
            cmc: string;
            clkx: string;
            clkk: string;
            clkp: string;
            clkt: string;
            clkw: string;
            wbs: string;
            pml: string;
            ppd: string;
            car: string;
            pcurl: string;
            dart: string;
            rdz: string;
            dbf: string;
            uvf: string;
            uvt: string;
            uvx: string;
            uvz: string;
            fe_launch: string;
            dna: string;
            mlp: string;
            dpg: string;
            dfac: string;
            kpxx: string;
            ait: string;
            svc: string;
            geo: string;
            mag: string;
            nml: string;
            esf: string;
            msf: string;
            qam: string;
            slt: string;
            ssf: string;
            es3: string;
            ez2: string;
            ez3: string;
            fdf: string;
            mseed: string;
            seed: string;
            gph: string;
            ftc: string;
            fm: string;
            fnc: string;
            ltf: string;
            fsc: string;
            oas: string;
            oa2: string;
            oa3: string;
            fg5: string;
            bh2: string;
            ddd: string;
            xdw: string;
            xbd: string;
            fzs: string;
            txd: string;
            ggb: string;
            ggt: string;
            gex: string;
            gxt: string;
            g2w: string;
            g3w: string;
            gmx: string;
            gdoc: string;
            gslides: string;
            gsheet: string;
            kml: string;
            kmz: string;
            gqf: string;
            gac: string;
            ghf: string;
            gim: string;
            grv: string;
            gtm: string;
            tpl: string;
            vcg: string;
            hal: string;
            zmm: string;
            hbci: string;
            les: string;
            hpgl: string;
            hpid: string;
            hps: string;
            jlt: string;
            pcl: string;
            pclxl: string;
            "sfd-hdstx": string;
            mpy: string;
            afp: string;
            irm: string;
            sc: string;
            icc: string;
            igl: string;
            ivp: string;
            ivu: string;
            igm: string;
            xpw: string;
            i2g: string;
            qbo: string;
            qfx: string;
            rcprofile: string;
            irp: string;
            xpr: string;
            fcs: string;
            jam: string;
            rms: string;
            jisp: string;
            joda: string;
            ktz: string;
            karbon: string;
            chrt: string;
            kfo: string;
            flw: string;
            kon: string;
            kpr: string;
            ksp: string;
            kwd: string;
            htke: string;
            kia: string;
            kne: string;
            skp: string;
            sse: string;
            lasxml: string;
            lbd: string;
            lbe: string;
            "123": string;
            apr: string;
            pre: string;
            nsf: string;
            org: string;
            scm: string;
            lwp: string;
            portpkg: string;
            mvt: string;
            mcd: string;
            mc1: string;
            cdkey: string;
            mwf: string;
            mfm: string;
            flo: string;
            igx: string;
            mif: string;
            daf: string;
            dis: string;
            mbk: string;
            mqy: string;
            msl: string;
            plc: string;
            txf: string;
            mpn: string;
            mpc: string;
            xul: string;
            cil: string;
            cab: string;
            xls: string;
            xlam: string;
            xlsb: string;
            xlsm: string;
            xltm: string;
            eot: string;
            chm: string;
            ims: string;
            lrm: string;
            thmx: string;
            msg: string;
            cat: string;
            stl: string;
            ppt: string;
            ppam: string;
            pptm: string;
            sldm: string;
            ppsm: string;
            potm: string;
            docm: string;
            dotm: string;
            wps: string;
            wpl: string;
            xps: string;
            mseq: string;
            mus: string;
            msty: string;
            taglet: string;
            nlu: string;
            ntf: string;
            nnd: string;
            nns: string;
            nnw: string;
            ngdat: string;
            "n-gage": string;
            rpst: string;
            rpss: string;
            edm: string;
            edx: string;
            ext: string;
            odc: string;
            otc: string;
            odb: string;
            odf: string;
            odft: string;
            odg: string;
            otg: string;
            odi: string;
            oti: string;
            odp: string;
            otp: string;
            ods: string;
            ots: string;
            odt: string;
            odm: string;
            ott: string;
            oth: string;
            xo: string;
            dd2: string;
            obgx: string;
            oxt: string;
            osm: string;
            pptx: string;
            sldx: string;
            ppsx: string;
            potx: string;
            xlsx: string;
            xltx: string;
            docx: string;
            dotx: string;
            mgp: string;
            dp: string;
            esa: string;
            pdb: string;
            paw: string;
            str: string;
            ei6: string;
            efif: string;
            wg: string;
            plf: string;
            pbd: string;
            box: string;
            mgz: string;
            qps: string;
            ptid: string;
            qxd: string;
            rar: string;
            bed: string;
            mxl: string;
            musicxml: string;
            cryptonote: string;
            cod: string;
            rm: string;
            rmvb: string;
            link66: string;
            st: string;
            see: string;
            sema: string;
            semd: string;
            semf: string;
            ifm: string;
            itp: string;
            iif: string;
            ipk: string;
            twd: string;
            mmf: string;
            teacher: string;
            fo: string;
            sdkm: string;
            dxp: string;
            sfs: string;
            sdc: string;
            sda: string;
            sdd: string;
            smf: string;
            sdw: string;
            sgl: string;
            smzip: string;
            sm: string;
            wadl: string;
            sxc: string;
            stc: string;
            sxd: string;
            std: string;
            sxi: string;
            sti: string;
            sxm: string;
            sxw: string;
            sxg: string;
            stw: string;
            sus: string;
            svd: string;
            sis: string;
            xsm: string;
            bdm: string;
            xdm: string;
            ddf: string;
            tao: string;
            pcap: string;
            tmo: string;
            tpt: string;
            mxs: string;
            tra: string;
            ufd: string;
            utz: string;
            umj: string;
            unityweb: string;
            uoml: string;
            vcx: string;
            vsd: string;
            vis: string;
            vsf: string;
            wbxml: string;
            wmlc: string;
            wmlsc: string;
            wtb: string;
            nbp: string;
            wpd: string;
            wqd: string;
            stf: string;
            xar: string;
            xfdl: string;
            hvd: string;
            hvs: string;
            hvp: string;
            osf: string;
            osfpvg: string;
            saf: string;
            spf: string;
            cmp: string;
            zir: string;
            zaz: string;
            vxml: string;
            wasm: string;
            wif: string;
            wgt: string;
            hlp: string;
            wsdl: string;
            wspolicy: string;
            "7z": string;
            abw: string;
            ace: string;
            dmg: string;
            arj: string;
            aab: string;
            aam: string;
            aas: string;
            bcpio: string;
            torrent: string;
            blb: string;
            bz: string;
            bz2: string;
            cbr: string;
            vcd: string;
            cfs: string;
            chat: string;
            pgn: string;
            crx: string;
            cco: string;
            nsc: string;
            cpio: string;
            csh: string;
            deb: string;
            dgc: string;
            dir: string;
            wad: string;
            ncx: string;
            dtb: string;
            res: string;
            dvi: string;
            evy: string;
            eva: string;
            bdf: string;
            gsf: string;
            psf: string;
            pcf: string;
            snf: string;
            pfa: string;
            arc: string;
            spl: string;
            gca: string;
            ulx: string;
            gnumeric: string;
            gramps: string;
            gtar: string;
            hdf: string;
            php: string;
            install: string;
            iso: string;
            jardiff: string;
            jnlp: string;
            kdbx: string;
            latex: string;
            luac: string;
            lzh: string;
            run: string;
            mie: string;
            prc: string;
            application: string;
            lnk: string;
            wmd: string;
            wmz: string;
            xbap: string;
            mdb: string;
            obd: string;
            crd: string;
            clp: string;
            exe: string;
            mvb: string;
            wmf: string;
            mny: string;
            pub: string;
            scd: string;
            trm: string;
            wri: string;
            nc: string;
            pac: string;
            nzb: string;
            pl: string;
            p12: string;
            p7b: string;
            p7r: string;
            rpm: string;
            ris: string;
            sea: string;
            sh: string;
            shar: string;
            swf: string;
            xap: string;
            sql: string;
            sit: string;
            sitx: string;
            srt: string;
            sv4cpio: string;
            sv4crc: string;
            t3: string;
            gam: string;
            tar: string;
            tcl: string;
            tex: string;
            tfm: string;
            texinfo: string;
            obj: string;
            ustar: string;
            hdd: string;
            ova: string;
            ovf: string;
            vbox: string;
            "vbox-extpack": string;
            vdi: string;
            vhd: string;
            vmdk: string;
            src: string;
            webapp: string;
            der: string;
            fig: string;
            xlf: string;
            xpi: string;
            xz: string;
            z1: string;
            xaml: string;
            xav: string;
            xca: string;
            xdf: string;
            xel: string;
            xns: string;
            xenc: string;
            xhtml: string;
            xml: string;
            dtd: string;
            xop: string;
            xpl: string;
            xsl: string;
            xspf: string;
            mxml: string;
            yang: string;
            yin: string;
            zip: string;
            "3gpp": string;
            adp: string;
            amr: string;
            au: string;
            mid: string;
            mxmf: string;
            mp3: string;
            m4a: string;
            mpga: string;
            oga: string;
            s3m: string;
            sil: string;
            uva: string;
            eol: string;
            dra: string;
            dts: string;
            dtshd: string;
            lvp: string;
            pya: string;
            ecelp4800: string;
            ecelp7470: string;
            ecelp9600: string;
            rip: string;
            wav: string;
            weba: string;
            aac: string;
            aif: string;
            caf: string;
            flac: string;
            mka: string;
            m3u: string;
            wax: string;
            wma: string;
            ram: string;
            rmp: string;
            ra: string;
            xm: string;
            cdx: string;
            cif: string;
            cmdf: string;
            cml: string;
            csml: string;
            xyz: string;
            ttc: string;
            otf: string;
            ttf: string;
            woff: string;
            woff2: string;
            exr: string;
            apng: string;
            avci: string;
            avcs: string;
            avif: string;
            bmp: string;
            cgm: string;
            drle: string;
            emf: string;
            fits: string;
            g3: string;
            gif: string;
            heic: string;
            heics: string;
            heif: string;
            heifs: string;
            hej2: string;
            hsj2: string;
            ief: string;
            jls: string;
            jp2: string;
            jpeg: string;
            jph: string;
            jhc: string;
            jpm: string;
            jpx: string;
            jxr: string;
            jxra: string;
            jxrs: string;
            jxs: string;
            jxsc: string;
            jxsi: string;
            jxss: string;
            ktx: string;
            ktx2: string;
            png: string;
            btif: string;
            pti: string;
            sgi: string;
            svg: string;
            t38: string;
            tif: string;
            tfx: string;
            psd: string;
            azv: string;
            uvi: string;
            djvu: string;
            sub: string;
            dwg: string;
            dxf: string;
            fbs: string;
            fpx: string;
            fst: string;
            mmr: string;
            rlc: string;
            ico: string;
            dds: string;
            mdi: string;
            wdp: string;
            npx: string;
            b16: string;
            tap: string;
            vtf: string;
            wbmp: string;
            xif: string;
            pcx: string;
            webp: string;
            "3ds": string;
            ras: string;
            cmx: string;
            fh: string;
            jng: string;
            sid: string;
            pic: string;
            pnm: string;
            pbm: string;
            pgm: string;
            ppm: string;
            rgb: string;
            tga: string;
            xbm: string;
            xpm: string;
            xwd: string;
            "disposition-notification": string;
            u8msg: string;
            u8dsn: string;
            u8mdn: string;
            u8hdr: string;
            eml: string;
            wsc: string;
            "3mf": string;
            gltf: string;
            glb: string;
            igs: string;
            msh: string;
            mtl: string;
            stpx: string;
            stpz: string;
            stpxz: string;
            dae: string;
            dwf: string;
            gdl: string;
            gtw: string;
            mts: string;
            ogex: string;
            x_b: string;
            x_t: string;
            vds: string;
            usdz: string;
            bsp: string;
            vtu: string;
            wrl: string;
            x3db: string;
            x3dv: string;
            x3d: string;
            appcache: string;
            ics: string;
            coffee: string;
            css: string;
            csv: string;
            html: string;
            jade: string;
            jsx: string;
            less: string;
            markdown: string;
            mml: string;
            mdx: string;
            n3: string;
            txt: string;
            dsc: string;
            rtx: string;
            sgml: string;
            shex: string;
            slim: string;
            spdx: string;
            stylus: string;
            tsv: string;
            t: string;
            ttl: string;
            uri: string;
            vcard: string;
            curl: string;
            dcurl: string;
            mcurl: string;
            scurl: string;
            ged: string;
            fly: string;
            flx: string;
            gv: string;
            "3dml": string;
            spot: string;
            jad: string;
            wml: string;
            wmls: string;
            vtt: string;
            s: string;
            c: string;
            htc: string;
            f: string;
            hbs: string;
            java: string;
            lua: string;
            mkd: string;
            nfo: string;
            opml: string;
            p: string;
            pde: string;
            sass: string;
            scss: string;
            etx: string;
            sfv: string;
            ymp: string;
            uu: string;
            vcs: string;
            vcf: string;
            yaml: string;
            "3gp": string;
            "3g2": string;
            h261: string;
            h263: string;
            h264: string;
            m4s: string;
            jpgv: string;
            mj2: string;
            ts: string;
            mp4: string;
            mpeg: string;
            ogv: string;
            qt: string;
            uvh: string;
            uvm: string;
            uvp: string;
            uvs: string;
            uvv: string;
            dvb: string;
            fvt: string;
            mxu: string;
            pyv: string;
            uvu: string;
            viv: string;
            webm: string;
            f4v: string;
            fli: string;
            flv: string;
            m4v: string;
            mkv: string;
            mng: string;
            asf: string;
            vob: string;
            wm: string;
            wmv: string;
            wmx: string;
            wvx: string;
            avi: string;
            movie: string;
            smv: string;
            ice: string;
        };
        ObjectUtil: {
            isEmpty(value: any): boolean;
        };
        DesensitizedUtil: {
            of(str: string, startIndex?: number, length?: number, pad?: string): string;
            reserve(str: string, headLen?: number, tailLen?: number, pad?: string): string;
            with(params: import("./modules/string/DesensitizedUtil").DesensitizedParam): string;
            mobile(str: string, startIndex?: number, length?: number, pad?: string): string;
            fullName(str: string, startIndex?: number, length?: number, pad?: string): string;
            fullName2(str: string): string;
            idCard(str: string, headLen?: number, tailLen?: number, pad?: string): string;
            bankAccount(str: string, headLen?: number, tailLen?: number, pad?: string): string;
            mobileWith(params: import("./modules/string/DesensitizedUtil").DesensitizedParam): string;
            fullNameWith(params: import("./modules/string/DesensitizedUtil").DesensitizedParam): string;
            idCardWith(params: import("./modules/string/DesensitizedUtil").DesensitizedReserveParam): string;
            bankAccountWith(params: import("./modules/string/DesensitizedUtil").DesensitizedReserveParam): string;
        };
        ArrayUtil: {
            repeat(arr: (string | number)[], count: number): string;
            finalItem(arr: any[], defaultItem?: any): any;
            push(arr: any[], item: any): any[];
        };
        PatternPool: PatternPool;
        PatternPollClass: typeof PatternPool;
        ValidateUtil: {
            validate(str: string, pattern: string | RegExp): boolean;
            isNumber(str: string): boolean;
            isChinese(str: string): boolean;
            isIPV4(str: string): boolean;
            isIPV6(str: string): boolean;
            isMoney(str: string): boolean;
            isEmail(str: string): boolean;
            isDomainName(str: string): boolean;
            isMobile(str: string): boolean;
            isLandline(str: string): boolean;
            isIdCard(str: string): boolean;
            isUrlHttp(str: string): boolean; /**
             * 数字工具
             */
            isPlateNumber(str: string): boolean;
            isDate(str: string): boolean;
            isTime(str: string): boolean;
            isBlankLine(str: string): boolean;
        };
        Ternary: typeof Ternary;
    };
}
declare const _default: Baitu;
export default _default;
