import Str from "./modules/string/Str";
import StrUtil from "./modules/string/StrUtil";
import DateTime, { DateField, MonthField, WeekDay } from "./modules/dateTime/DateTime";
import DateUtil from "./modules/dateTime/DateUtil";
import NumberUtil from "./modules/number/NumberUtil";
import Num from "./modules/number/Num";
import Throttle from "./modules/common/Throttle";
import Debounce from "./modules/common/Debounce";
import FileUtil from "./modules/file/FileUtil";
import FileTypeMagicMap from "./modules/file/FileTypeMagicMap";
import FileTypeMimeMap from "./modules/file/FileTypeMimeMap";
import HexUtil from "./modules/common/HexUtil";
import ObjectUtil from "./modules/object/ObjectUtil";
import DesensitizedUtil from "./modules/string/DesensitizedUtil";
import ArrayUtil from "./modules/array/ArrayUtil";
import PatternPool from "./modules/common/PatternPool";
import ValidateUtil from "./modules/string/ValidateUtil";
import ImgUtil from "./modules/file/ImgUtil";
import IDUtil from "./modules/common/IDUtil";
import SnowflakeIdWorker from "./modules/common/SnowflakeIdWorker";
import EncryptUtil from "./modules/common/EncryptUtil";
import JSONUtil, { JSONType } from "./modules/common/JSONUtil";
import UrlUtil from "./modules/common/UrlUtil";
import TreeUtil from "./modules/common/TreeUtil";
import ExePool from "./modules/execute/ExePool";
import Executes from "./modules/execute/Executes";
import ChineseDateUtil from "./modules/dateTime/chinese/ChineseDateUtil";
import ChineseDate from "./modules/dateTime/chinese/ChineseDate";
export { Str, StrUtil, DateTime, DateField, WeekDay, MonthField, DateUtil, Num, NumberUtil, Throttle, Debounce, FileUtil, HexUtil, FileTypeMagicMap, FileTypeMimeMap, ObjectUtil, DesensitizedUtil, ArrayUtil, PatternPool, ValidateUtil, ImgUtil, IDUtil, SnowflakeIdWorker, EncryptUtil, JSONUtil, JSONType, UrlUtil, TreeUtil, ExePool, Executes, ChineseDateUtil, ChineseDate };
declare const Baitu: {
    Str: typeof Str;
    StrUtil: import("./modules/string/StrUtil").StrUtil;
    DateTime: typeof DateTime;
    DateField: typeof DateField;
    WeekDay: typeof WeekDay;
    MonthField: typeof MonthField;
    DateUtil: import("./modules/dateTime/DateUtil").DateUtil;
    Num: typeof Num;
    NumberUtil: import("./modules/number/NumberUtil").NumberUtil;
    Throttle: typeof Throttle;
    Debounce: typeof Debounce;
    FileUtil: import("./modules/file/FileUtil").FileUtil;
    HexUtil: import("./modules/common/HexUtil").HexUtil;
    FileTypeMagicMap: import("./modules/file/FileTypeMagicMap").FileTypeMagicMap;
    FileTypeMimeMap: import("./modules/file/FileTypeMimeMap").FileTypeMimeMap;
    ObjectUtil: import("./modules/object/ObjectUtil").ObjectUtil;
    DesensitizedUtil: import("./modules/string/DesensitizedUtil").DesensitizedUtil;
    ArrayUtil: import("./modules/array/ArrayUtil").ArrayUtil;
    PatternPool: import("./modules/common/PatternPool").PatternPool;
    ValidateUtil: import("./modules/string/ValidateUtil").ValidateUtil;
    ImgUtil: import("./modules/file/ImgUtil").ImgUtil;
    IDUtil: {
        uuid(simple?: boolean): string;
        snowflake(workerId?: number, dataCenterId?: number): SnowflakeIdWorker;
    };
    SnowflakeIdWorker: typeof SnowflakeIdWorker;
    EncryptUtil: {
        Base64: import("./modules/common/EncryptUtil").Base64Class;
        MD5: (str: string) => string;
        RSA: typeof import("./modules/common/EncryptUtil").RSA;
        AES: {
            new (secretKey: string): {
                secretKey: string;
                iv: string;
                mode: any;
                padding: any;
                pads: {
                    Pkcs7: any;
                    Ansix923: any;
                    Iso10126: any;
                    Iso97971: any;
                    NoPadding: any;
                    ZeroPadding: any;
                };
                mods: {
                    CFB: any;
                    CTR: any;
                    CTRGladman: any;
                    ECB: any;
                    OFB: any;
                };
                setPadding(padding: any): void;
                setMode(mode: any): void;
                encode(str: string): string;
                decode(str: string): string;
            };
            build(secretKey: string): {
                secretKey: string;
                iv: string;
                mode: any;
                padding: any;
                pads: {
                    Pkcs7: any;
                    Ansix923: any;
                    Iso10126: any;
                    Iso97971: any;
                    NoPadding: any;
                    ZeroPadding: any;
                };
                mods: {
                    CFB: any;
                    CTR: any;
                    CTRGladman: any;
                    ECB: any;
                    OFB: any;
                };
                setPadding(padding: any): void;
                setMode(mode: any): void;
                encode(str: string): string;
                decode(str: string): string;
            };
        };
    };
    JSONUtil: import("./modules/common/JSONUtil").JSONUtil;
    UrlUtil: import("./modules/common/UrlUtil").UrlUtil;
    TreeUtil: import("./modules/common/TreeUtil").TreeUtil;
    ExePool: typeof ExePool;
    Executes: {
        sleep(millis: number): Promise<unknown>;
        toPromise(fun: Function | Promise<any>): Promise<any>;
        toPromiseClosure(fun: Function | Promise<any>): () => Promise<any>;
        exe(fun: Function | Promise<any>): Promise<any>;
    };
    ChineseDateUtil: {
        JRW: string[];
        numCn: string[];
        Gan: string[];
        Zhi: string[];
        ShX: string[];
        Jq: string[];
        Ym: string[];
        Rm: string[];
        Yxm: string[];
        JRB: string[][];
        JNB: (string | number)[];
        getFestival(year: number, month: number, day: number): import("./modules/dateTime/chinese/ChineseDateUtil").FestivalInfo;
        getFestivalByDayAllInfo(dayAllInfo: import("./modules/dateTime/chinese/ChineseDateUtil").DayAllInfo): import("./modules/dateTime/chinese/ChineseDateUtil").FestivalInfo;
        getChineseZodiac(chineseYear: number): string;
        getGan(chineseYear: number): string;
        getZhi(chineseYear: number): string;
        getCyclical(chineseYear: number): string;
        getHuangdiYear(chineseYear: number): number;
        getDynasty(year: number): import("./modules/dateTime/chinese/ChineseDateUtil").DynastyInfo;
        getMonthDays(year: number, month: number): import("./modules/dateTime/chinese/ChineseDateUtil").DayAllInfo[];
        getMonthInfo(chineseYear: number, chineseMonth: number): import("./modules/dateTime/chinese/ChineseDateUtil").MonthInfo;
        getDaySimpleInfo(year: number, month: number, day: number): import("./modules/dateTime/chinese/ChineseDateUtil").DayAllInfo;
        getDayAllInfo(year: number, month: number, day: number): import("./modules/dateTime/chinese/ChineseDateUtil").DayAllInfo;
        getSolarTermsInfo(year: number, month: number, day: number): import("./modules/dateTime/chinese/ChineseDateUtil").SolarTermsInfo;
        qi_accurate(W: any): number;
        so_accurate(W: any): number;
        lunar2solar(chineseYear: number, chineseMonth: number, chineseDay: number): Date;
    };
    ChineseDate: typeof ChineseDate;
    setPatternPool(patternPool: import("./modules/common/PatternPool").PatternPool): void;
};
export default Baitu;
