import Str from "./modules/string/Str";
import DateTime, { DateField, MonthField, WeekDay } from "./modules/dateTime/DateTime";
import Num from "./modules/number/Num";
import Throttle from "./modules/common/Throttle";
import Debounce from "./modules/common/Debounce";
import { PatternPool } from "./modules/common/PatternPool";
declare const _default: {
    Str: typeof Str;
    StrUtil: import("./modules/string/StrUtil").StrUtil;
    DateTime: typeof DateTime;
    DateField: typeof DateField;
    WeekDay: typeof WeekDay;
    MonthField: typeof MonthField;
    DateUtil: import("./modules/dateTime/DateUtil").DateUtil;
    Num: typeof Num;
    NumberUtil: import("./modules/number/NumberUtil").NumberUtil;
    Throttle: typeof Throttle;
    Debounce: typeof Debounce;
    FileUtil: import("./modules/file/FileUtil").FileUtil;
    HexUtil: import("./modules/base/HexUtil").HexUtil;
    FileTypeMagicMap: import("./modules/file/FileTypeMagicMap").FileTypeMagicMap;
    FileTypeMimeMap: import("./modules/file/FileTypeMimeMap").FileTypeMimeMap;
    ObjectUtil: import("./modules/object/ObjectUtil").ObjectUtil;
    DesensitizedUtil: import("./modules/string/DesensitizedUtil").DesensitizedUtil;
    ArrayUtil: import("./modules/array/ArrayUtil").ArrayUtil;
    PatternPool: PatternPool;
    ValidateUtil: import("./modules/string/ValidateUtil").ValidateUtil;
    ImgUtil: import("./modules/file/ImgUtil").ImgUtil;
    setPatternPool(patternPool: PatternPool): void;
};
export default _default;
